#{{{ execute file path
PATH=/usr/sbin:/usr/local/sbin:/usr/local/bin:$PATH
PATH=/home/bin:$HOME/bin:$PATH
#}}}

# {{{ development environment
# export QT_SELECT=qt4

# [[[ Path
# Lantern
PATH=$HOME/.lantern/bin:$PATH
# Hugo
PATH=$HOME/bin/hugo:$PATH
# Scripts
PATH=$HOME/bin/scripts:$PATH
PATH=$HOME/bin/scripts/bashell:$PATH
PATH=$HOME/bin/scripts/python:$PATH
PATH=$HOME/bin/scripts/perl:$PATH
# installed pip packages
PATH=$HOME/.local/bin:$PATH
# ]]]

# [[[ ARM cross_compile toolchains
# PATH=/opt/crosstool-ng/bin:$PATH
PATH=$HOME/Embedded/ok6410/tools/dnw2:$PATH
PATH=$HOME/Embedded/ok6410/toolchains/arm-1176jzfs-linux-gnueabihf/bin:$PATH
# ]]]

# [[[ ccache speedup build time
export PATH="/usr/lib/ccache/bin:$PATH"
export set USE_CCACHE=1
export set CCACHE_DIR=$HOME/Data/Development/IDE/CCC/CCACHE/CacheDir
export set CCACHE_LOGFILE=$HOME/Data/Development/IDE/CCC/CCACHE/CacheDir/CCache.log
# Tell ccache to only use compilers here
export set CCACHE_PATH="/usr/bin"
# ]]]

# [[[ colored gcc output (work with ccache)
# As per usual colorgcc installation, leave unchanged (don't add ccache)
PATH="/usr/lib/colorgcc/bin:$PATH"
# alias gcc="colorgcc"
# alias g++="colorgcc"
# ]]]

# [[[ texlive env
# TEXLIVEPATH=$HOME/Data/Development/Runtime/LaTeX/2015
# PATH=$TEXLIVEPATH/bin/x86_64-linux:$PATH
# MANPATH=$TEXLIVEPATH/texmf-dist/doc/man:$MANPATH
# INFOPATH=$TEXLIVEPATH/texmf-dist/doc/info:$INFOPATH
# ]]]

# [[[ Math Work
# # Matlab
# PATH=$HOME/bin/Matlab:$PATH
# # Mathematica
# PATH=$HOME/bin/Mathematica:$PATH
# ]]]

# [[[ Android Development
# Add environment variable ANDROID_SDK_ROOT
export ANDROID_SDK_ROOT=$HOME/lib/Android/sdk
export PATH=$ANDROID_SDK_ROOT/tools:$PATH
export PATH=$ANDROID_SDK_ROOT/platform-tools:$PATH
# ]]]
# }}}

# {{{ JAVA CLASS path
# export JAVA_HOME=/usr/lib/jvm/oracle-jdk-bin-1.8
# export JAVA_HOME=/usr/lib/jvm/icedtea-bin-7
# export CLASSPATH=.:$JAVA_HOME/lib/dt.jar:$HOME/lib/java:$JAVA_HOME/lib/tools.jar
# export CLASSPATH=$HOME/lib/Java:$CLASSPATH
# }}}

# {{{ Go
# export GOPATH=/
# }}}
