# Path to your oh-my-zsh configuration.
ZSH=$HOME/.sysconf/zsh_conf/oh-my-zsh
DEFAULT_USER=nopcall

# custom config dir environment
DATA=$HOME/Data
SYSCONF_DIR=$HOME/.sysconf/
SYSCONF_ZSH_DIR=$SYSCONF_DIR/zsh_conf

# zsh theme
source $SYSCONF_ZSH_DIR/zshrc.theme

# oh-my-zsh plugins dependence on platform
if [ `uname` = 'Linux' ]; then
    plugins=(autojump git history-substring-search knife key-bindings)
else if [ `uname` = 'Darwin' ]; then
         plugins=(brew autojump git history-substring-search knife key-bindings)
     fi
fi

# source oh-my-zsh environment
source $ZSH/oh-my-zsh.sh

# environment
source $SYSCONF_ZSH_DIR/zshrc.env
# functions
source $SYSCONF_ZSH_DIR/zshrc.func
# zsh plus
source $SYSCONF_ZSH_DIR/zshrc.plus
# source alias
source $SYSCONF_ZSH_DIR/zshrc.alias

#{{{ special system
# Ubuntu
if [[ $(lsb_release -is 2>/dev/null) == "Ubuntu" ]] ; then
    source $SYSCONF_ZSH_DIR/zshrc.ubuntu
fi
# Gentoo
if [[ $(lsb_release -is 2>/dev/null) == "Gentoo" ]] ; then
    source $SYSCONF_ZSH_DIR/zshrc.gentoo
fi
# Mac
if [ `uname` = 'Darwin' ]; then
    source $SYSCONF_ZSH_DIR/zshrc.mac
fi
#}}}

# Customize to your needs...
# setxkbmap -option terminate:ctrl_alt_bksp
if [[ -f ~/.zshrc.local ]]; then
	source $HOME/.zshrc.local
fi
