# Path to your oh-my-zsh configuration.
ZSH=$HOME/.sysconf/zsh_conf/oh-my-zsh
DEFAULT_USER=`whoami`
# report to me when people login/logout
watch=(notme)

# config dir path
SYSCONF_DIR=$HOME/.sysconf
SYSCONF_ZSH_DIR=$SYSCONF_DIR/zsh_conf

# zsh theme
source $SYSCONF_ZSH_DIR/zshrc.theme

# oh-my-zsh plugins dependence on platform
plugins=(taskwarrior tmux colored-man-pages docker autojump git sudo history-substring-search)

# source oh-my-zsh environment
source $ZSH/oh-my-zsh.sh

# environment
source $SYSCONF_ZSH_DIR/zshenv
# functions
source $SYSCONF_ZSH_DIR/zshrc.func
# zsh plus
source $SYSCONF_ZSH_DIR/zshrc.plus
# source alias
source $SYSCONF_ZSH_DIR/zshrc.alias
# fix HHKB numpad
source $SYSCONF_ZSH_DIR/zshrc.hhkb

# Gentoo
source $SYSCONF_ZSH_DIR/zshrc.gentoo

# local
[[ -f ~/.zshrc.local ]] && source $HOME/.zshrc.local
